[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

# dynamic linking on debug for compile time
[tasks.build-development]
condition = { profiles = [ "development" ] }
command = "cargo"
args = ["build", "--features", "bevy/dynamic"]

[tasks.build-production]
condition = { profiles = [ "production" ] }
command = "cargo"
args = ["build", "--release"]
dependencies = ["format"]

[tasks.build]
clear = true
dependencies = [
    "build-development",
    "build-production",
]

[tasks.run-development]
condition = { profiles = [ "development" ] }
command = "cargo"
args = ["run"]

[tasks.run-production]
condition = { profiles = [ "production" ] }
command = "cargo"
args = ["run", "--release"]


[tasks.run]
dependencies = [
    "build",
    "run-development",
    "run-production",
]
